# Generated by Django 5.2 on 2025-04-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
