# Generated by Django 5.2 on 2025-04-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_advertisement_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='active',
        ),
    ]
