# Generated by Django 5.2 on 2025-04-28 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_remove_advertisement_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_trending',
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.category'),
        ),
    ]
